### ISSUE TITLE
Hangs in quarkus dev mode 

### ISSUE THREAD

**Issue by belkevglaz** [quarkiverse/quarkus-rabbitmq-client#19]
Hi @bpasson.
I tried to use your extension and faced with weird issue. 
When I ran the application as in dev mode, it can't stop due to hangs. 
I checked thread dump and found that shutdown thread waits extensions logic. 
```
"Shutdown thread" #58 prio=5 os_prio=0 tid=0x00007f7024004800 nid=0x67d11 in Object.wait() [0x00007f70ebefc000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x0000000775c4bd58> (a com.rabbitmq.utility.BlockingValueOrException)
	at java.lang.Object.wait(Object.java:502)
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:49)
	- locked <0x0000000775c4bd58> (a com.rabbitmq.utility.BlockingValueOrException)
	at com.rabbitmq.utility.BlockingCell.get(BlockingCell.java:64)
	- locked <0x0000000775c4bd58> (a com.rabbitmq.utility.BlockingValueOrException)
	at com.rabbitmq.utility.BlockingCell.uninterruptibleGet(BlockingCell.java:120)
	- locked <0x0000000775c4bd58> (a com.rabbitmq.utility.BlockingValueOrException)
	at com.rabbitmq.utility.BlockingValueOrException.uninterruptibleGetValue(BlockingValueOrException.java:36)
	at com.rabbitmq.client.impl.AMQChannel$BlockingRpcContinuation.getReply(AMQChannel.java:502)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1115)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1034)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1018)
	at com.rabbitmq.client.impl.AMQConnection.close(AMQConnection.java:1010)
	at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.close(AutorecoveringConnection.java:280)
	at io.quarkiverse.rabbitmqclient.RabbitMQClientImpl.lambda$disconnect$1(RabbitMQClientImpl.java:66)
	at io.quarkiverse.rabbitmqclient.RabbitMQClientImpl$$Lambda$745/1321952240.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at io.quarkiverse.rabbitmqclient.RabbitMQClientImpl.disconnect(RabbitMQClientImpl.java:61)
	at io.quarkiverse.rabbitmqclient.RabbitMQClients.destroy(RabbitMQClients.java:70)
	at io.quarkiverse.rabbitmqclient.runtime.RabbitMQRecorder$$Lambda$602/1865549678.run(Unknown Source)
	at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:83)
	at io.quarkus.runtime.StartupContext.close(StartupContext.java:72)
	at io.quarkus.runner.ApplicationImpl.doStop(ApplicationImpl.zig:928)
	at io.quarkus.runtime.Application.stop(Application.java:188)
	at io.quarkus.runtime.Application.stop(Application.java:140)
	at io.quarkus.runtime.ApplicationLifecycleManager$ShutdownHookThread.run(ApplicationLifecycleManager.java:360)
```

Check the source and not found any potential roots of cause.
This problem will not be allowed to fully use quarkus's hot-swap and fast development
Could you please help to investigate and solve it ? 
Thanks.

**Comment by bpasson** [comment]
Thanks for reporting the issue. Can you supply a small example that reproduces the issue?

**Comment by belkevglaz** [comment]
Hi @bpasson 
I prepared simple [project](https://github.com/belkevglaz/quarkus-rmq-extension-hang-issue.git) that does nothing. No amqp consumers or rest entry points deliberately. Only initalization on startup.
I use Idea 2020.3.3 to run application in Quarkus Dev mode. Start and stop from idea run configuration. After stop - java app process hangs and should be killed to be able run again.

**Comment by bpasson** [comment]
@belkevglaz you might have to help me a bit here. I'm not a heavy Gradle user, prefer Maven. When I want to have IntelliJ build your example project it fails with the following message.

```
Starting Gradle Daemon...
Gradle Daemon started in 1 s 103 ms

FAILURE: Build failed with an exception.

* Where:
Build file '/projects/quarkus-rmq-extension-hang-issue/build.gradle' line: 34

* What went wrong:
A problem occurred evaluating root project 'quarkus-rmq-extension-hang-issue'.
> java.lang.NullPointerException (no error message)
```
I probably have something not set up correctly. Any pointers?

**Comment by belkevglaz** [comment]
@bpasson probably you are run on JDK 11 that does not have tools.jar. You can comment 1 and 34 rows (with mentions about tools.jar) or run on JDK8.

**Comment by bpasson** [comment]
@belkevglaz I was running GraalVM Java 11. Switching to 8 fixed it.

**Comment by bpasson** [comment]
@belkevglaz playing around with your project in Quarkus Dev mode it seems the RabbitMQ Java client never seems to get a reponse from the server on connection closing. I have no idea why this happens. I need to do some further investigation. A workaround is adding a timeout on the connection close method, but that could possibly have unwanted side effects.

**Comment by bpasson** [comment]
@belkevglaz ok small update. Further digging lead me to the ManagedExecutor which is used when creating the client in stead of the client default. If using the managed executor it hangs, if not it terminates. Not sure why yet.

**Comment by belkevglaz** [comment]
@bpasson one more finding. If run application in dev mode with debug (green bug icon) that looks like threads not hanged. I tried several times default run and in debug - and in all debug cases application can stop. 
I guess that something wrong with thread management and even debug can affect it.

**Comment by bpasson** [comment]
@belkevglaz I noticed that too, but presumably the connection was already closed as the heartbeat fails at 60s and the connection closes after which debug mode terminates perfectly. I haven't figured out what the difference is in running with a user defined executor service (quarkus managed executor) or a client managed executor service.

**Comment by bpasson** [comment]
@belkevglaz right, I did extensive test runs and it seem to be related to the managed executor. I honestly have no idea what is. The intention to use it is for having context propagation with the consumer actions.

**Comment by bpasson** [comment]
@belkevglaz I have a workaround for now, until a definite solution is found. I'll add a timeout when dev-mode is active to make sure the connection is closed always.

**Comment by belkevglaz** [comment]
@bpasson made this timeout configurable, please.

**Comment by belkevglaz** [comment]
Thanks
